### ISSUE TITLE
Spoon screenshot not showing up on the report?

### ISSUE THREAD

**Issue by cooperkong** [neoranga55/espresso-cucumber#1]
Hi, 
Thanks for the great work.
Just wondering did you #ever get Spoon screenshot working with Cucumber + Espresso, I can see the screenshot being taken and pulled to build/spoon/images folder, but can't get the images showing on the Spoon report.

Thanks.

**Comment by sebaslogen** [comment]
Hi,
Yes, this line below is where I use cucumber embed() method to embed all the image content directly into the html report:
https://github.com/neoranga55/espresso-cucumber/blob/master/espresso-test-lib/EspressoInstrumentation/src/com/tomtom/espresso/test/CucumberHelperTestSteps.java#L86

**Comment by cooperkong** [comment]
Thanks for the reply, does this embed method adds the images to the Cucumber HTML report or the Spoon HTML report?
Thanks

**Comment by sebaslogen** [comment]
This attaches the screenshot to the cucumber report which is the runner executing the tests.

I assume that if you want the Spoon report you'll need to switch to the Spoon runner and he will generate the report. So you have to make a choice between running the test in parallel on multiple devices or using the cucumber BDD language.

**Comment by cooperkong** [comment]
That's interesting, because I have configured Cucumber to run with Spoon. Basically if you do "./gradlew spoon", it deploys the tests to all connected devices and generates a Spoon reports at the end. Anyway, I have got the screenshot display in the Spoon report :), [here](https://github.com/cooperkong/ACucumberSpoonScreenshots) is a sample project I made.

Cheers,

**Comment by sebaslogen** [comment]
Awesome, I haven't used Spoon for multi-device execution but it's fantastic to know they can work together so well :+1:
